---
name: 'Render Config Files'
description: 'Renders files from Jinja2 templates'
author: 'rhl@jfm.dk'
inputs:
  working-directory:
    description: 'The working directory to run the action in, any files under this directory matching the extension will be rendered.'
    default: ${{ github.workspace }}
    required: false
  template-extension:
    description: 'File extension of templates (default "production")'
    default: production
    required: false
  vars:
    description: 'JSON string encoded map of variables for use in templates'
    default: '{}'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.working-directory }}
    - ${{ inputs.template-extension }}
    - ${{ inputs.vars }}
